### ISSUE TITLE
Updating fails

### ISSUE THREAD

**Issue by bb010g** [dinsfire64/PonyMotes#1]
Running "Update Database" gives a "PonyMotes Update": "There was a connection error." error. "Help" and "About" are also broken. This is due to dinsfire.com currently being down. If you don't want to host this content anymore, perhaps it could be done with GitHub Pages?

**Comment by dinsfire64** [comment]
This was a mistake in the nginx configuration on the server. It has been resolved, please attempt to update again.

**Comment by bb010g** [comment]
Yep, that works now. Thanks so much for maintaining all this!

(Off-topic, but any chance the repo could get updated to what's on the Play store soon?)

**Comment by dinsfire64** [comment]
Man I wish I could, I actually lost the updates in a harddrive crash. My stupidity for not backing up the latest version.

**Comment by bb010g** [comment]
Oof. I hope the decompiler smiles on you if you have to go that way to fix something in the future.
